### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /home/zoads/public_html/survival/stats/classes/bluestats.class.php on line 10

### ISSUE THREAD

**Issue by zoads** [robinp7720/Blue-Stats-Minecraft#28]
Hey,

I just installed this on my webserver and I am getting this error on the main root page, just wondering what it means, I went through the toubleshooting and edited this http://puu.sh/kZjQJ/6bf066c59e.png to how it is now (manually because your quiery was giving errors) and this didnt fix it. I tried the other troubleshooting steps and it changed nothing.

**Comment by zoads** [comment]
I changed that line to this: public $plugins = "lolmewinstats"; and then it fixed that error and its now producing this one, that I am unsure how to fix: Parse error: syntax error, unexpected '[' in /home/zoads/public_html/survival/stats/classes/bluestats.class.php on line 15

**Comment by robinp7720** [comment]
Don't modify anything in the source. The Parse error: syntax error, unexpected '[' in /home/zoads/public_html/survival/stats/classes/bluestats.class.php on line 15 error is caused by you making a mistake. I cannot and will not help anyone that doesn't give me an error log or error report.

If the server query isn't working a you mentioned, please make sure that you have enabled MC query on the minecraft server and that the IP and port is correct.
