### ISSUE TITLE
Error 500 on main page

### ISSUE THREAD

**Issue by krustymk** [robinp7720/Blue-Stats-Minecraft#38]
All appear to install fine,.

I can access the Admin page though i cannot change the theme.. No drop down menu or other way to select an alternative, just delete the text and write a name of an alternative theme. Though it just reverts to Material when you click 'Submit'
The home page just returns a 500 (ive tried RewriteEngine Off, RewriteBase /Stats/) no parent .htaccess
When in the admin page and Logout is clicked, it just goes to a blank page.
When i try to access the home page i just get the following error (My IP removed)

000.000.000.000 - - [23/Apr/2016:16:48:12 +0200] "GET /Stats/ HTTP/1.0" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"

Thanks for your help

**Comment by robinp7720** [comment]
There is no submit button for the single line options. Just press enter on your keyboard. As per the 500 error thats probably a dependancy error for which I will need an error for.

**Comment by JialuZhang** [comment]
@krustymk 

Please do not include
```
RewriteEngine Off
```
along in your configuration, otherwise the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
