### ISSUE TITLE
Getting a error 500 after install

### ISSUE THREAD

**Issue by MinecraftB0ss** [robinp7720/Blue-Stats-Minecraft#39]
error.log: http://pastebin.com/iQvtTZ4H

Ive tried installing to multiple directories, also set owner to apache, and manually copying the .css file in theme assets to the assets folder..

It lets me go to the admin panel just fine, its just when i view the main page. Not sure what may be causing it.

**Comment by btnalexandre** [comment]
Yes i have the same error ! An issue plz ?

**Comment by mwoelk** [comment]
Seems to be an error with the query plugin. Disabling it by removing it from the list of plugins in the admin area helped in my case.

**Comment by robinp7720** [comment]
The problem is indeed caused, in the new version after an install at least, by the query plugin but only if the ip and port entered are incorrect. The first solution should be to verify your server ip and port, not disabling it completely.

**Comment by mwoelk** [comment]
Yes, you're right. I just found out we had queries disabled on the server. It could help future users to show a hint during installation ;)

**Comment by robinp7720** [comment]
@mwoelk will do. Would definitely reduce the amount of issues people have after installation.

**Comment by poblabs** [comment]
@robinp7720 I'm getting this same error. After I installed, I get error 500 and no stylesheets or anything load. I've followed the `.htaccess` instructions as well as changing the URL since I'm not installed into root. 

Removing the `query` folder from the plugins folder has broken the site completely now. Moving it to a subdomain and changing the URLs back render the same error 500. 

Any other way to troubleshoot this error 500? Nothing shows up in my Apache error logs.
