### ISSUE TITLE
Highscores/AllPlayers not found

### ISSUE THREAD

**Issue by MARODEUR** [robinp7720/Blue-Stats-Minecraft#60]
Hi there,

after finishing the Installation of BlueStats (All Successful) i can only view the "Home" page.
When i want to watch a specific player or just the highscores for example, i got an "Error 404 Not Found". 

Any ideas?

**Comment by robinp7720** [comment]
Please read the README.md
No error log, no help.

**Comment by MARODEUR** [comment]
there you go...
http://pastebin.com/gVy0wxvV

Need something else?

**Comment by robinp7720** [comment]
Please note that I have decided to not help with these sort of problems anymore. This a problem which is caused by your webserver and misconiguration of BlueStats. Instructions on how to fix these problems can be found on the wiki and in previous issues.

The reason I am saying this is because many others are having the same problems. Please see this issue on the incorrect htaccess file: https://github.com/robinp7720/Blue-Stats-Minecraft/issues/59 and the wiki https://github.com/robinp7720/Blue-Stats-Minecraft/wiki/Troubleshooting on how to setup the url configuration.
