### ISSUE TITLE
User unfriendly display of large numbers

### ISSUE THREAD

**Issue by crysis992** [robinp7720/Blue-Stats-Minecraft#70]
Hey, 

Some stats have a strange formatting when it comes to high values.
(Using the latest dev/commit version, but also happens on release-stage versions)

Currently, my "Damage Taken" statistic looks like this: 3.0625411197468E+39
Or my "Blocks travelled": 3849997.2325946 (Should be rounded to full blocks?)

My stats site is located here: https://crytec.net/stats/home/ If you need to take a look yourself.

**Comment by robinp7720** [comment]
I can add the option to round the blocks traveled to the nearest full number. But of the damage taken I don't know what I can could do apart from telling your players to stop killing each other <sup>/s</sup>

The weird number occurred because the number is so high. It's about 3<sup>39</sup> which is well, a very big number. I could add logarithmic scaling to the values but that may trouble some users. Any user friendly method of displaying such a number is welcome.

**Comment by robinp7720** [comment]
Ok, stat values are now rounded to the nearest whole number. Any suggestions for displaying extremely large numbers is still appreciated.

**Comment by crysis992** [comment]
I'm a php n00b but this is simple and working:
I've added this to bubbleStats.php
`$server_total = sprintf('%.2f', $server_total);`

right after 
```
        if ($statName == "playtime") {
            $server_total = secondsToTime($server_total, false);
            $server_average = secondsToTime($server_average, false);
        } else {
			$server_total = sprintf('%.2f', $server_total);
		}
```

And this to the css:
`word-wrap: break-word;`

The layout need some tweaks, since some bubbles will be bigger when a line break occurs, but yea.
This is just a idea, not sure if it is usefull or not xD I basically know nothing about webdesign/php

result: https://puu.sh/tJho5/e382c5a39c.png

**Comment by robinp7720** [comment]
Ok, I just committed a solution for the large numbers. Instead of displaying large numbers, numbers will be abbreviated using K, M, B, T, Qa, Qi. Won't be as specific as your suggestion but much more human readable.
